### ISSUE TITLE
client/redis_discovery.go pairsMu RUnlock of unlocked RWMutex

### ISSUE THREAD

**Issue by exuan** [smallnest/rpcx#529]
```go

discovery := client.NewRedisDiscovery(
	"/service",
	"test", []string{"127.0.0.1:6379"},
	&store.Config{Password: "admin", Bucket: "1"},
)

log.Println(discovery.GetServices())

```

```
fatal error: sync: RUnlock of unlocked RWMutex

goroutine 1 [running]:
runtime.throw(0x140e20e, 0x21)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc00063fbb8 sp=0xc00063fb88 pc=0x439152
sync.throw(0x140e20e, 0x21)
	/usr/local/go/src/runtime/panic.go:1102 +0x35 fp=0xc00063fbd8 sp=0xc00063fbb8 pc=0x469a55
sync.(*RWMutex).rUnlockSlow(0xc000448020, 0xc0bfffffff)
	/usr/local/go/src/sync/rwmutex.go:80 +0x3f fp=0xc00063fc00 sp=0xc00063fbd8 pc=0x48911f
sync.(*RWMutex).RUnlock(0xc000448020)
	/usr/local/go/src/sync/rwmutex.go:70 +0x49 fp=0xc00063fc20 sp=0xc00063fc00 pc=0x4890c9
github.com/smallnest/rpcx/client.(*RedisDiscovery).GetServices(0xc000448000, 0xc0005ba180, 0x1, 0x1)
	/home/xuan/go/pkg/mod/github.com/smallnest/rpcx@v0.0.0-20201208110353-181ddf2f622b/client/redis_discovery.go:128 +0xa6 fp=0xc00063fc58 sp=0xc00063fc20 pc=0x10a4e66

```

**Comment by smallnest** [comment]
It is my fault and. I have fixed. thanks
