### ISSUE TITLE
client hangs after sync call to server (one in 5000 times)

### ISSUE THREAD

**Issue by glycerine** [smallnest/rpcx#572]
As I'm stress testing my server using rpcx on the server, and rpcx on the client, I notice that, for about 1 in 5000 calls, the client will hang in the spot shown below (stack trace from kill -QUIT).  The server has received the synchronous request, and replied. However the client never thinks the call is complete, and just hangs forever.

I wonder if you could advise on how to go about solving this?

It does seem to be a bug somewhere (probably a race, since it happens infrequently), in the rpcx client implementation.  

I am on ubuntu 18.04 on this commit:

~~~
commit d969a5f620f8383be39d17007b29dfd93983a819 (HEAD -> master, origin/master, origin/HEAD)
Merge: a54ce65 54101b2
Author: smallnest <smallnest@gmail.com>
Date:   Sat Mar 13 11:21:52 2021 +0800

    Merge pull request #562 from fly512/master
~~~

the stack trace is always the same:
~~~
SIGQUIT: quit
PC=0x4732c1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x102b508, 0x80, 0x0, 0x0, 0x0, 0xc00003a800, 0xc000128008, 0x113920e2022c03, 0x7fffcb1fb128, 0x40db5f, ...)
	/usr/local/go1.15.7/src/runtime/sys_linux_amd64.s:587 +0x21
runtime.futexsleep(0x102b508, 0x0, 0xffffffffffffffff)
	/usr/local/go1.15.7/src/runtime/os_linux.go:45 +0x46
runtime.notesleep(0x102b508)
	/usr/local/go1.15.7/src/runtime/lock_futex.go:159 +0x9f
runtime.stopm()
	/usr/local/go1.15.7/src/runtime/proc.go:1924 +0xc5
runtime.findrunnable(0xc00003a800, 0x0)
	/usr/local/go1.15.7/src/runtime/proc.go:2485 +0xa7f
runtime.schedule()
	/usr/local/go1.15.7/src/runtime/proc.go:2683 +0x2d7
runtime.park_m(0xc000000300)
	/usr/local/go1.15.7/src/runtime/proc.go:2851 +0x9d
runtime.mcall(0x94fa00)
	/usr/local/go1.15.7/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [select]:
github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client.(*Client).call(0xc0002be750, 0xaff840, 0xc0002bc900, 0xa558a0, 0x11, 0xa4cadc, 0x5, 0x981d80, 0xc0002bc8a0, 0x981e80, ...)
	/home/jaten/go/src/github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client/client.go:240 +0x23c
github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client.(*Client).Call(...)
	/home/jaten/go/src/github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client/client.go:231
main.(*ClientRpcx).DoSyncCallWithContext(0xc0002be680, 0xaff7c0, 0xc000026170, 0xc0002dc000, 0x0, 0xc0002e4900, 0x2f1, 0x2f1, 0x0, 0x0)
	/home/jaten/go/src/github.com/glycerine/goq/xc.go:169 +0x219
main.(*ClientRpcx).DoSyncCall(...)
	/home/jaten/go/src/github.com/glycerine/goq/xc.go:137
main.(*Submitter).SubmitJobGetReply(0xc00012e6c0, 0xc0002dc000, 0x1, 0xc00013d860, 0xc0002dc000, 0x0, 0x400, 0x7fc18e1d1700)
	/home/jaten/go/src/github.com/glycerine/goq/sub.go:86 +0xbb
main.main()
	/home/jaten/go/src/github.com/glycerine/goq/main.go:169 +0x221f

goroutine 21 [IO wait]:
internal/poll.runtime_pollWait(0x7fc18c3d0d48, 0x72, 0xaf7180)
	/usr/local/go1.15.7/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000123f18, 0x72, 0xaf7100, 0xfe5680, 0x0)
	/usr/local/go1.15.7/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go1.15.7/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000123f00, 0xc0002d8000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go1.15.7/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc000123f00, 0xc0002d8000, 0x4000, 0x4000, 0x7fc18c1ea878, 0x7fc18c1ea878, 0x60)
	/usr/local/go1.15.7/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00011c218, 0xc0002d8000, 0x4000, 0x4000, 0x0, 0x0, 0x0)
	/usr/local/go1.15.7/src/net/net.go:182 +0x8e
bufio.(*Reader).Read(0xc00010f1a0, 0xc00030a004, 0x1, 0xc, 0x203000, 0x203000, 0x203000)
	/usr/local/go1.15.7/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0xaf5c00, 0xc00010f1a0, 0xc00030a004, 0x1, 0xc, 0x1, 0x201, 0x1000000000000, 0x7fc18c1ea878)
	/usr/local/go1.15.7/src/io/io.go:314 +0x87
io.ReadFull(...)
	/usr/local/go1.15.7/src/io/io.go:333
github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/protocol.(*Message).Decode(0xc000318000, 0xaf5c00, 0xc00010f1a0, 0xc000200060, 0x0)
	/home/jaten/go/src/github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/protocol/message.go:401 +0x7a
github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client.(*Client).input(0xc0002be750)
	/home/jaten/go/src/github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client/client.go:502 +0xd0
created by github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client.(*Client).Connect
	/home/jaten/go/src/github.com/glycerine/goq/vendor/github.com/smallnest/rpcx/client/connection.go:56 +0x1ff

rax    0xca
rbx    0x102b3c0
rcx    0x4732c3
rdx    0x0
rdi    0x102b508
rsi    0x80
rbp    0x7fffcb1fb0f0
rsp    0x7fffcb1fb0a8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x3
r13    0x102ae80
r14    0x4
r15    0x11
rip    0x4732c1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
~~~

This is where the client is making the call. The source code is open source:

https://github.com/glycerine/goq/blob/master/xc.go#L140

**Comment by smallnest** [comment]
I looks  using a xclient goroutine to call the server, right?

**Comment by glycerine** [comment]
> I looks you used a xclient goroutine to call the server, right?
yes, that's right

> And are there any logs in server side?
um, not at the moment. The operation completes at the server.  What kind of logs would you like?  If there is a way to instrument the rpcx server portion that would be helpful here, just let me know what to try.

**Comment by smallnest** [comment]
I want to make sure whether the reply was sent to the client. It it failed to send, it should print some errors in the default logger. 
If you have not configured the customized logger, rpcx should print logs on stdout/stderr

**Comment by smallnest** [comment]
You can upgrade rpcx to the  latest commit and set `github.com/smallnest/rpcx/share.Trace = true` in client and server sides.

It prints each key trace logs about requests and responses in log so you can check why the response has not reached the client and where it has been dropped.

**Comment by smallnest** [comment]
And if there is any info in logs, you can use https://github.com/smallnest/rpcxdump to capture network data in client side and server side.

**Comment by glycerine** [comment]
great suggestions, thank you! I'll try these as soon as I can -- might be tomorrow since I'm swamped today.

**Comment by smallnest** [comment]
no more feedback. closed

**Comment by glycerine** [comment]
hmm. I've haven't found time to get back to this, but it certainly isn't resolved on my end.
