### ISSUE TITLE
客户端关闭后，服务进程写入writeChan异常退出

### ISSUE THREAD

**Issue by zsinx** [smallnest/rpcx#625]
测试代码如下
**server**：
```
var (
	addr     = flag.String("addr", "localhost:8972", "server address")
	etcdAddr = flag.String("etcdAddr", "localhost:2379", "etcd address")
	basePath = flag.String("base", "/rpcx_test", "prefix path")
)

func main() {
	flag.Parse()

	s := server.NewServer()
	r := &serverplugin.EtcdV3RegisterPlugin{
		ServiceAddress: "tcp@" + *addr,
		EtcdServers:    []string{*etcdAddr},
		BasePath:       *basePath,
		UpdateInterval: time.Minute,
	}
	s.Plugins.Add(r)

	s.RegisterName("Arith", new(Arith), "")
	err := s.Serve("tcp", *addr)
	if err != nil {
		panic(err)
	}
}

type Args struct {
	A int
	B int
}

type Reply struct {
	C int
}

type Arith struct{}

func (t *Arith) Mul(ctx context.Context, args *Args, reply *Reply) error {
	time.Sleep(4 * time.Second) // 模拟超时
	reply.C = args.A * args.B
	fmt.Printf("call: %d * %d = %d\n", args.A, args.B, reply.C)
	return nil
}
```

**client**：
```
var (
	etcdAddr = flag.String("etcdAddr", "localhost:2379", "etcd address")
	basePath = flag.String("base", "/rpcx_test", "prefix path")
)

func main() {
	flag.Parse()

	option := client.DefaultOption
	// 设置了服务端响应超时时间为3秒
	option.IdleTimeout = 3 * time.Second

	d, _ := etcd_client.NewEtcdV3Discovery(*basePath, "Arith", []string{*etcdAddr}, false, nil)
	xclient := client.NewXClient("Arith", client.Failover, client.RoundRobin, d, option)
	defer xclient.Close()

	args := &example.Args{
		A: 10,
		B: 20,
	}

	reply := &example.Reply{}
	err := xclient.Call(context.Background(), "Mul", args, reply)
	if err != nil {
		log.Printf("failed to call: %v\n", err)
		return
	}

	log.Printf("%d * %d = %d", args.A, args.B, reply.C)
}
```

测试步骤：
1，启动server
2，启动client

测试结果：
服务端进程异常退出，异常日志如下
```
2021/08/12 09:48:09 server.go:198: INFO : server pid:3896
2021/08/12 09:48:47 server.go:426: INFO : client has closed this connection: 127.0.0.1:52319
call: 10 * 20 = 200
panic: send on closed channel

goroutine 16 [running]:
github.com/smallnest/rpcx/server.(*Server).serveConn.func2(0xc00014c300, 0xc000186cc0, 0xc00018a050, 0xc00018a048, 0x1924f60, 0xc0003f4000)
	C:/Users/ZHANG/go/pkg/mod/github.com/smallnest/rpcx@v1.6.6/server/server.go:553 +0x1248
created by github.com/smallnest/rpcx/server.(*Server).serveConn
	C:/Users/ZHANG/go/pkg/mod/github.com/smallnest/rpcx@v1.6.6/server/server.go:479 +0x18ba

Debugger finished with exit code 0
```

**Comment by smallnest** [comment]
这个当前的rpcx没有这个问题，你确保拉去最新的rpcx

**Comment by hanyue2020** [comment]
1.6.8 也有问题
![Screenshot_20210813_094619](https://user-images.githubusercontent.com/5828315/129293364-8d9d9f78-29ee-4111-8a9d-415c838da200.png)

**Comment by smallnest** [comment]
用1.6.9
